
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;
import "BattleUnit.sol";


contract Warrior  {
    
    uint static public warriorAttack;
    uint static public warriorDefense;

    uint public warnum = 5;
    address public warriorAddress = address(this);

    constructor() public {
        require(tvm.pubkey() != 0, 101);
        require(msg.pubkey() == tvm.pubkey(), 102);
        tvm.accept();
    }

    function getAddress() virtual public returns (address){
        return warriorAddress;
    }
}
