
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "Gibdd.sol";

//interface Registable {
//    function registCar(address regCar) external;
//}

contract Car {

    uint public tvmPubkey;
    uint public msgPubkey;

    address public msgAddress;

    uint public doors;

    //uint static public carNumber;

    constructor(uint _doors) public {
        tvm.accept();
        doors = _doors;
    }

    function sendCarToGibdd(Gibdd gibddAddress) public {
        tvm.accept();
        gibddAddress.registCar(this);

    }

    function checkKeysAdnAddress () public {
        tvm.accept();
        tvmPubkey = tvm.pubkey();
        msgPubkey = msg.pubkey();

        msgAddress = msg.sender;
    }

  
}
//0:b52f0e19c9ac1ab16a627acf4e03f8ce28b489f53d28f2831e7e5228b94d74f9 - GIBDD
//0:4484c09eb9401666d5a858924af319b9a70aede3ba52c8c05d84774486659f83 - Car

//0:465a013e5d8dd0f4c648fd3c931590098f0950aa29a516903249b36922ef212f