
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

contract map_opt {
    
    mapping (uint=>uint) myMap;
    
    constructor() public {
        require(tvm.pubkey() != 0, 101);
        require(msg.pubkey() == tvm.pubkey(), 102);
        tvm.accept();
        myMap[4] = 9;
        myMap[20] = 15;
        myMap[3] = 7;
        myMap[8] = 13;
        myMap[55] = 1;      
    }

    function renderHelloWorld () public pure returns (string) {
        return 'helloWorld';
    }

    function getList() public returns (uint[]) {
        tvm.accept();
        optional(uint, uint) currentOpt = myMap.min();
        uint[] resArr;

        while (currentOpt.hasValue()) {
            (uint key, uint val) = currentOpt.get();
            resArr.push(val);
            currentOpt = myMap.next(key);
        }

        return resArr;
    }
}
