
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

contract SampleToken {
   
    struct Token {
        string name;
        uint power;
    }

    Token[] tokensArr;
    mapping (uint=>uint) tokenToOwner;

    function ctreateToken(string name, uint power) public {
        // проверка прав на создание
        tvm.accept();
        tokensArr.push(Token(name, power));
        uint keyAsLastNum = tokensArr.length - 1;
        tokenToOwner[keyAsLastNum] = msg.pubkey();
        //транслировать событие emit MyEvent
 }

    function getTokenOwner(uint tokenID) public view returns (uint) {
        // tvm.accept();
        return tokenToOwner[tokenID];
    }

    function getTokenInfo(uint tokenID) public view returns (string tokenName, uint tokenPower) {
        tokenName = tokensArr[tokenID].name;
        tokenPower = tokensArr[tokenID].power;

    }

    function changeOwner(uint tokenID, uint pubkeyOfNewOwner) public {
        require(msg.pubkey() == tokenToOwner[tokenID], 101);
        tvm.accept();
        tokenToOwner[tokenID] = pubkeyOfNewOwner;
    }

    constructor() public {
        require(tvm.pubkey() != 0, 101);
       
        require(msg.pubkey() == tvm.pubkey(), 102);
        tvm.accept();

    }
}
